# Generated by Django 5.2.5 on 2025-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hiring_companies/')),
                ('name', models.CharField(max_length=255)),
                ('company_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
