# Generated by Django 5.2.5 on 2025-08-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_industry_subindustry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_areas', to='jobs.subindustry')),
            ],
            options={
                'unique_together': {('sub_industry', 'name')},
            },
        ),
    ]
