# Generated by Django 5.2.5 on 2025-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_functionalarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('area_of_interest', models.CharField(blank=True, max_length=255)),
                ('resume', models.FileField(upload_to='candidate_resumes/')),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
