# Generated by Django 5.2.5 on 2025-08-28 11:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_candidatedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_keyword', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('seo_description', ckeditor.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
